channels:
- pytorch
- conda-forge
- defaults
dependencies:
- cudatoolkit=11.3.1
- python=3.9.17
- pytorch=1.10.1
- torchvision=0.11.2
- pip:
  - accelerate==0.21.0
  - annotated-types==0.5.0
  - appdirs==1.4.4
  - attrs==23.1.0
  - autopep8==2.0.2
  - certifi==2023.7.22
  - charset-normalizer==3.2.0
  - cityscapesscripts==2.2.2
  - click==8.1.6
  - coloredlogs==15.0.1
  - contourpy==1.1.0
  - cycler==0.11.0
  - docker-pycreds==0.4.0
  - einops==0.6.1
  - einops-exts==0.0.4
  - ema-pytorch==0.2.3
  - filelock==3.12.2
  - fonttools==4.41.1
  - fsspec==2023.6.0
  - gitdb==4.0.10
  - gitpython==3.1.32
  - huggingface-hub==0.16.4
  - humanfriendly==10.0
  - idna==3.4
  - importlib-resources==6.0.0
  - jsonlines==3.1.0
  - kiwisolver==1.4.4
  - kornia==0.6.12
  - matplotlib==3.7.2
  - packaging==23.1
  - pathtools==0.1.2
  - protobuf==4.23.4
  - psutil==5.9.5
  - pycodestyle==2.11.0
  - pydantic==2.1.1
  - pydantic-core==2.4.0
  - pyparsing==3.0.9
  - pyquaternion==0.9.9
  - python-dateutil==2.8.2
  - pytorch-warmup==0.1.1
  - pyyaml==6.0.1
  - regex==2023.6.3
  - requests==2.31.0
  - safetensors==0.3.1
  - sentencepiece==0.1.99
  - sentry-sdk==1.28.1
  - setproctitle==1.3.2
  - smmap==5.0.0
  - tokenizers==0.13.3
  - tomli==2.0.1
  - tqdm==4.65.0
  - transformers==4.31.0
  - typing==3.7.4.3
  - urllib3==2.0.4
  - wandb==0.15.7
  - zipp==3.16.2
